---
- name: Update installed packages with yum
  yum:
    name: '*'
    update_cache: yes
    state: latest
  when:
    - ansible_distribution == 'CentOS'
    - upgrade_packages|bool
  tags: upgrade_packages|bool

- name: Update installed packages with apt 
  apt:
    upgrade: dist
    update_cache: yes
    state: latest
  tags: upgrade_packages
  when:
    - ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    - upgrade_packages|bool

- name: Updated installed packages with dnf
  dnf:
    name: '*'
    state: latest
  when:
    - ansible_distribution == 'Fedora' or ansible_distribution == 'AlmaLinux'
    - upgrade_packages|bool
  tags: upgrade_packages|bool

- name: Install basic packages for {{ ansible_distribution }}
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages | default([]) }}"
  tags: basic_packages

- name: Install custom packages for {{ ansible_hostname }}
  package:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('present') }}"
  with_dict: "{{ custom_packages | default({}) }}"
  ignore_errors: yes
